name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: test echo ls
      run: ls -la
      
    - name: make
      run: make

    - name: test output
      run: ./a.out
